sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
git:
    submodules: false
branches:
  only:
    - main # build master branch only
install:
  - npm install
script:
  - hexo clean # hexo clean db.json
  - hexo generate # generate static files
deploy:
  provider: pages
  # skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public